### ISSUE TITLE
All change under Unrelease

### ISSUE THREAD

**Issue by nguyentanhungbk** [heinrichreimer/action-github-changelog-generator#31]
Hi,

Currently my project flow GitFlow.
- all PR is merge into develop branch (develop is default branch of git hub repo)
- release will be on master branch (tag is created on this branch)

with above setup, every time I run this action, all change log is under the Un release.

**Comment by Ismoh** [comment]
I have the same issue. It's because the comparison is done between the tag and HEAD, but I dont know what HEAD is right now and if there is a way to change the comparison of unreleased stuff to a specific branch. In my and your case, it should be 'develop'.

**Comment by Ismoh** [comment]
I change the main branch from master to develop, beacuse I am creating tag based on develops commit history. This fixed the issue.

@heinrichreimer Would be awesome, if we can add the base/head branch we would like to compare unrealeased stuff.
(click on full change log of unrealeased and change in the url the branch you would like to compare instead of have `some_branch...your_latest_branch` instead of `some_branch...HEAD`)

**Comment by heinrichreimer** [comment]
Unfortunately I won't be able to work on this anytime soon. So I would be happy if you could just submit a pull request 🙂

**Comment by Ismoh** [comment]
Could be possible that I have a look some day.
But after taking a while, thinking about it, I think the workflow isn't correct, when creating changelog on develop. We'll see!
